### ISSUE TITLE
就没人用白鹭的广告吗? 连应用都不能添加，放出来干嘛？

### ISSUE THREAD

**Issue by fly-studio** [runinspring/egretAD#1]
![image](https://user-images.githubusercontent.com/8188778/35142378-16c4fde8-fd39-11e7-8ce2-1e9312d6b58d.png)

本来我是冲着你们能激励广告来的，但是：

- 第一次打开后台慢的离谱
- 打开之后，应用都无法添加：
  - 输入什么URL都是错误
  - 保存按钮为什么有2个？
- 还有那个整体报表，为什么打开就有初始数据。

请问这都是HTML页面吗？都没做好 放出来干嘛？

**Comment by shangbielian** [comment]
首先 感谢 你给我们提出的问题，我们也在 加紧 进行 问题的 处理 ，给你带来的 不便，真的对不起。因为 毕竟 平台刚做出来 会有一些问题，也希望大家 多对我们的平台提出问题和意见。谢谢。

**Comment by maybesomethinghappened** [comment]
在了解到您提出的问题之后，我们现阶段已经修复您说的一系列问题，十分抱歉对您的工作产生的诸多不便，您现可重新访问并使用平台。我们也会听取广大用户提出宝贵的意见和建议，谢谢！

**Comment by fly-studio** [comment]
您好，两位大佬，看到你们那么迅速的解决问题很感欣慰，

但是必须要点击 「检测」按钮 之后，才可以点击「保存」，是否可以添加相关文本帮助，不然普通用户可能直接点击了保存，而反复的会提示 「请检查你的URL」。
另外，我们这个游戏会打包成app，这个网址是否就是一个非必要的字段？

另外，很期待egret能尽快上激励视频类的广告，毕竟这个才是当前免费小游戏收入的大头。

**Comment by maybesomethinghappened** [comment]
再次对您提出的意见表示感谢，我们的技术小伙伴对此已经做出了相应的修改，关于游戏打包成微端的情况下，网址也是一个必要的字段。您也可以通过上方滚动导航栏提供的邮箱地址(zhangdongtao@egret.com)，通过邮件的形式联系到我们，我们的商务小伙伴会向您提供相关的接入文档，让您更方便更快捷的使用我们白鹭的广告服务，谢谢！

**Comment by fly-studio** [comment]
另外发现如下问题

### Windows 10 + Chrome 63

1. 添加广告位时，banner类的广告无法指定在页面顶部或者是底部，或者只能添加到顶部？
2. 提取代码 的 弹出窗体， 只要鼠标点击，哪怕点击到文本框，都会被关闭，影响复制代码。
只有将鼠标拖放到窗体外才能让窗体保留。

### 如果使用`egretad.min.js`的方式在第三方网页上面添加广告代码时

1. 我的站点是HTTPS，但是会请求的是一个非HTTPS资源导致出错
```
 egretad.min.js:1 Mixed Content: The page at 'https://www.我的域名.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'https://ssp.egret.com/api/ad/getAd?ad_id=209'. This request has been blocked; the content must be served over HTTPS..
```
2. 非HTTPS站点，添加：`new egretad.AD(209);`，会跨域提示
```
Failed to load http://ssp.egret.com/api/ad/getAd?ad_id=209: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://我的域名' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by maybesomethinghappened** [comment]
我们的技术小伙伴已经收到了您提出的宝贵意见，正在对此进行测试检查。如果可以的话，您这边方便留一个邮箱或者是联系方式吗，我们在修改完之后会在第一时间向您发送反馈消息，再次感谢您选择我们白鹭的广告服务，谢谢！
