### ISSUE TITLE
5.1.x版本的可以使用吗

### ISSUE THREAD

**Issue by FifoGame** [runinspring/egretAD#2]

**Comment by runinspring** [comment]
可以用的

**Comment by FifoGame** [comment]
我创建新版本的helloworld,在main中无法使用 new egretad.AD

**Comment by runinspring** [comment]
我刚测试了，可以正常运行。你那报什么错误？

**Comment by FifoGame** [comment]
提示：can't find name ‘egretad’.

**Comment by runinspring** [comment]
这是没引用 egretad.js，配置第三方库了吗

**Comment by FifoGame** [comment]
能具体指导下怎么配置吗，5.1.x的有demo吗

**Comment by runinspring** [comment]
你邮箱发我，给你个demo。这个要联系商务部门给你分配广告 id 才能运行

**Comment by FifoGame** [comment]
2216971381@qq.com 我已经分配到id了 横幅广告测试正常

**Comment by runinspring** [comment]
邮件回复你了。我知道问题在哪了。引擎 5.1.x 需要在 tsconfig.json 里把第三方库也配置上
